"""Best ATR period and multiplier for Chandelier Exit (everget) on the 1D chart, Bybit BTCUSDT perpetual.

Same rules as chandelier_backtest.py (long on Buy, short on Sell or flat with long-only; signal on the close, fill at
the next open, 0.075% per side, 1x). The first 300 daily candles are warm-up, so trading starts in Jan 2021.
Settings are picked on train (Jan 2021 - Oct 2024) by PF averaged over the neighbouring settings, then checked on
test (Oct 2024 - Oct 2026).

    python3 scripts/chandelier_1d.py > backtests/chandelier_1d.md
"""
import itertools, os, sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import community_backtest as C  # noqa: E402

P = C.P
LENGTHS = (2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 18, 20, 22, 25, 28, 30, 35, 40, 45, 50, 60)
MULTS = tuple(round(1 + 0.25 * i, 2) for i in range(21))  # 1.0 ... 6.0
MIN_TRAIN_TRADES = 15


def fmt(r):
    return f"PF {min(r['pf'], 99):.2f}, {r['n']} trades, win {r['win']:.0f}%, {r['ret']:+.0f}%, DD {r['dd']:.0f}%"


def smooth(grid, i, j, w='train'):
    vals = [grid[(LENGTHS[a], MULTS[b])][w]['pf'] for a in range(max(0, i - 1), min(len(LENGTHS), i + 2))
            for b in range(max(0, j - 1), min(len(MULTS), j + 2))]
    return float(np.median(vals))


if __name__ == '__main__':
    candles = P.load('data', '1D')
    D = P.prepare(candles)
    t, c = D['t'], D['c']
    W = C.windows(t)
    W['full'] = (300, len(t))
    res = {}
    for u, side in itertools.product((True, False), ('both', 'long')):
        g = {}
        for n, k in itertools.product(LENGTHS, MULTS):
            tr = C.backtest(D, 'chandelier', dict(length=n, mult=k, use_close=u, filt=0, sl_atr=0, side=side))
            g[(n, k)] = {w: P.stats(t, tr, s, e) for w, (s, e) in W.items()}
        res[(u, side)] = g
    bh = {w: (c[e - 1] / c[s] - 1) * 100 for w, (s, e) in W.items()}
    print('# Chandelier Exit (everget) on 1D: ATR period × multiplier\n')
    print('Generated by `scripts/chandelier_1d.py`. Bybit BTCUSDT.P daily candles. Long on Buy, short on Sell (or flat '
          'when long only), signal on the close, fill at the next open, 0.075% per side, 1x. '
          f'{len(LENGTHS)} ATR periods × {len(MULTS)} multipliers × close / high-low extremes × both sides / long only. '
          f"Buy & hold: train {bh['train']:+.0f}%, test {bh['test']:+.0f}%, whole {bh['full']:+.0f}%.\n")
    print('## Best per variant (picked on train PF averaged over neighbouring settings)\n')
    print('| Extremes | Side | ATR / mult | Train | Test | Whole period |\n|---|---|---|---|---|---|')
    picks = {}
    for (u, side), g in res.items():
        best = None
        for i, n in enumerate(LENGTHS):
            for j, k in enumerate(MULTS):
                if g[(n, k)]['train']['n'] < MIN_TRAIN_TRADES:
                    continue
                sc = smooth(g, i, j)
                if best is None or sc > best[0]:
                    best = (sc, n, k)
        _, n, k = best
        picks[(u, side)] = (n, k)
        r = g[(n, k)]
        print(f"| {'close' if u else 'high/low'} | {side} | {n} / {k:g} | {fmt(r['train'])} | {fmt(r['test'])} | {fmt(r['full'])} |")
    print('\n## Most robust: highest weaker-of-train-and-test PF, averaged over neighbours (uses the test window)\n')
    print('| Extremes | Side | ATR / mult | Train | Test | Whole period |\n|---|---|---|---|---|---|')
    for (u, side), g in res.items():
        best = max(((min(smooth(g, i, j, 'train'), smooth(g, i, j, 'test')), n, k)
                    for i, n in enumerate(LENGTHS) for j, k in enumerate(MULTS)
                    if g[(n, k)]['train']['n'] >= MIN_TRAIN_TRADES))
        _, n, k = best
        r = g[(n, k)]
        print(f"| {'close' if u else 'high/low'} | {side} | {n} / {k:g} | {fmt(r['train'])} | {fmt(r['test'])} | {fmt(r['full'])} |")
    for u, side in ((True, 'both'), (True, 'long')):
        g = res[(u, side)]
        for w in ('train', 'test'):
            print(f"\n## {w.capitalize()} PF, {'close' if u else 'high/low'} extremes, {side} (rows: ATR period, columns: multiplier)\n")
            cols = MULTS[::2]
            print('| ATR | ' + ' | '.join(f'{k:g}' for k in cols) + ' |\n|---|' + '---|' * len(cols))
            for n in LENGTHS:
                print(f'| {n} | ' + ' | '.join(f"{min(g[(n, k)][w]['pf'], 9.99):.2f}" for k in cols) + ' |')
    print('\n## Default 22 / 3.0 for reference\n\n| Extremes | Side | Train | Test | Whole period |\n|---|---|---|---|---|')
    for (u, side), g in res.items():
        r = g[(22, 3.0)]
        print(f"| {'close' if u else 'high/low'} | {side} | {fmt(r['train'])} | {fmt(r['test'])} | {fmt(r['full'])} |")
