"""Chandelier Exit (everget) as a strategy on Bybit BTCUSDT perpetual. Needs numpy and data/bybit_15m.json.

Traded like the indicator's labels: long on Buy, short on Sell, always in the market (each signal reverses).
Signal on the close, fill at the next open, 0.075% per side (taker + slippage), 1x, full equity per trade.
Train Apr 2020 - Oct 2024, test Oct 2024 - Oct 2026.

    python3 scripts/chandelier_backtest.py > backtests/chandelier_exit.md
"""
import itertools, os, sys, time
from multiprocessing import Pool

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import community_backtest as C  # noqa: E402
from community_detail import resample  # noqa: E402

P, DAY = C.P, C.DAY
TFS = {'1H': 60, '2H': 120, '3H': 180, '4H': 240, '6H': 360, '8H': 480, '12H': 720, '1D': 1440}
LENGTHS = (10, 14, 22, 30, 44, 60)
MULTS = (1.5, 2.0, 2.5, 3.0, 4.0, 5.0)
DEFAULT = dict(length=22, mult=3.0, use_close=True)
G = {}


def init(D):
    G['D'] = D


def run(args):
    D = G['D']
    p, side = args
    tr = C.backtest(D, 'chandelier', dict(p, filt=0, sl_atr=0, side=side))
    W = C.windows(D['t'])
    return p, side, {w: P.stats(D['t'], tr, s, e) for w, (s, e) in dict(W, full=(300, len(D['t']))).items()}


def bh(D, s, e):
    return (D['c'][e - 1] / D['c'][s] - 1) * 100


def fmt(r):
    return f"PF {min(r['pf'], 99):.2f}, {r['per_year']:.0f}/yr, win {r['win']:.0f}%, {r['ret']:+.0f}%, DD {r['dd']:.0f}%"


if __name__ == '__main__':
    combos = [dict(length=a, mult=b, use_close=u) for a, b, u in itertools.product(LENGTHS, MULTS, (True, False))]
    jobs = [(p, side) for p in combos for side in ('both', 'long')]
    data, res = {}, {}
    for tf, m in TFS.items():
        D = P.prepare(resample(m))
        data[tf] = D
        with Pool(os.cpu_count(), initializer=init, initargs=(D,)) as pool:
            res[tf] = pool.map(run, jobs)
        print(f'{tf} done', file=sys.stderr, flush=True)
    key = lambda p: (p['length'], p['mult'], p['use_close'])
    print('# Chandelier Exit (everget) as a strategy, Bybit BTCUSDT perpetual\n')
    print('Generated by `scripts/chandelier_backtest.py`. Long on Buy, short on Sell, always in the market; signal on the '
          'close, fill at the next open; 0.075% per side, 1x. Train Apr 2020 – Oct 2024, test Oct 2024 – Oct 2026.\n')
    print('## Default settings (ATR 22, multiplier 3.0, close-based extremes) on every timeframe\n')
    print('| Chart | Side | Train | Test | Whole period | Buy & hold (whole) |\n|---|---|---|---|---|---|')
    for tf in TFS:
        D = data[tf]
        for p, side, r in res[tf]:
            if key(p) == key(DEFAULT):
                print(f"| {tf} | {side} | {fmt(r['train'])} | {fmt(r['test'])} | {fmt(r['full'])} | {bh(D, 300, len(D['t'])):+.0f}% |")
    print('\n## Best settings per timeframe, picked on train PF (smoothed over neighbouring length / multiplier)\n')
    print('| Chart | Side | Settings | Train | Test |\n|---|---|---|---|---|')
    picks = []
    for tf in TFS:
        for side in ('both', 'long'):
            rows = {key(p): r for p, sd, r in res[tf] if sd == side}
            best = None
            for (a, b, u), r in rows.items():
                if r['train']['n'] < 30:
                    continue
                ia, ib = LENGTHS.index(a), MULTS.index(b)
                nb = [rows[(LENGTHS[x], MULTS[y], u)]['train']['pf'] for x in range(max(0, ia - 1), min(len(LENGTHS), ia + 2))
                      for y in range(max(0, ib - 1), min(len(MULTS), ib + 2))]
                sc = float(np.median(nb))
                if best is None or sc > best[0]:
                    best = (sc, (a, b, u), r)
            if best:
                (a, b, u), r = best[1], best[2]
                picks.append((tf, side, a, b, u, r))
                print(f"| {tf} | {side} | {a} / {b:g} / {'close' if u else 'high-low'} | {fmt(r['train'])} | {fmt(r['test'])} |")
    print('\n## Test-window PF per setting, both sides, close-based (rows: ATR length, columns: multiplier)\n')
    for tf in ('2H', '4H', '6H', '12H'):
        rows = {key(p): r for p, sd, r in res[tf] if sd == 'both'}
        print(f'**{tf}**\n\n| length | ' + ' | '.join(f'{b:g}' for b in MULTS) + ' |\n|---|' + '---|' * len(MULTS))
        for a in LENGTHS:
            print(f'| {a} | ' + ' | '.join(f"{rows[(a, b, True)]['test']['pf']:.2f}" for b in MULTS) + ' |')
        print()
    print('## Share of settings with test PF > 1 (all 72 settings, per side)\n\n| Chart | Both sides | Long only |\n|---|---|---|')
    for tf in TFS:
        cells = []
        for side in ('both', 'long'):
            v = [r['test']['pf'] for p, sd, r in res[tf] if sd == side]
            cells.append(f'{100 * np.mean(np.array(v) > 1):.0f}% (median {np.median(v):.2f})')
        print(f'| {tf} | ' + ' | '.join(cells) + ' |')
