"""Chandelier Exit (everget) + ZLSMA (veryfid's Zero Lag LSMA) on Bybit BTCUSDT perpetual. Needs numpy.

ZLSMA(n) = lsma + (lsma - linreg(lsma, n)), lsma = linreg(close, n)  (offset 0, source close)

Variants (signal on the close, fill at the next open, 0.075% per side, 1x, full equity):
  ce              Chandelier Exit alone: long on Buy, short on Sell, always in the market
  filter          Buy only counts if close > ZLSMA (Sell only if close < ZLSMA); exit on the opposite CE signal
  filter_zlexit   filter + also exit when the close crosses back through the ZLSMA
  confirm         enter when the CE direction and the close vs ZLSMA first agree; exit when the CE flips
  confirm_zlexit  enter when they agree, exit as soon as either one disagrees
Train Apr 2020 - Oct 2024 (Jan 2021 on 1D, after the 300-candle warm-up), test Oct 2024 - Oct 2026.

    python3 scripts/chandelier_zlsma.py > backtests/chandelier_zlsma.md
"""
import os, sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import community_backtest as C  # noqa: E402

P = C.P
TFS = ('15m', '1H', '4H', '12H', '1D')
VARIANTS = ('ce', 'filter', 'filter_zlexit', 'confirm', 'confirm_zlexit')
CE_SETTINGS = ((22, 3.0), (40, 4.0))


def linreg(x, n):
    """ta.linreg(x, n, 0); nan until n valid values."""
    out = np.full(len(x), np.nan)
    first = int(np.argmax(~np.isnan(x)))
    out[first:] = P.linreg_end(x[first:], n)
    out[:first + n - 1] = np.nan
    return out


def zlsma(c, n):
    lsma = linreg(c, n)
    return 2 * lsma - linreg(lsma, n)


def ce_dir(D, length, mult):
    buy, sell = P.sig_chandelier(D, length, mult)
    d = np.zeros(len(buy))
    cur = 1
    for i in range(len(buy)):
        cur = 1 if buy[i] else -1 if sell[i] else cur
        d[i] = cur
    return buy, sell, d


def signals(D, variant, length, mult, zl_len, side):
    c = D['c']
    buy, sell, d = ce_dir(D, length, mult)
    zl = zlsma(c, zl_len)
    above, below = c > zl, c < zl
    if variant == 'ce':
        el, es, xl, xs = buy, sell, sell, buy
    elif variant.startswith('filter'):
        el, es, xl, xs = buy & above, sell & below, sell.copy(), buy.copy()
        if variant == 'filter_zlexit':
            xl, xs = xl | below, xs | above
    else:
        al, as_ = (d == 1) & above, (d == -1) & below
        el, es = al & ~np.r_[False, al[:-1]], as_ & ~np.r_[False, as_[:-1]]
        xl, xs = (d == -1), (d == 1)
        if variant == 'confirm_zlexit':
            xl, xs = ~al, ~as_
    if side == 'long':
        es = np.zeros(len(c), bool)
    sig = np.where(el, 1, np.where(es, -1, 0))
    sig[:300] = 0
    nan = np.full(len(c), np.nan)
    return sig, xl, xs, nan


def run(D, variant, length, mult, zl_len, side):
    sig, xl, xs, nan = signals(D, variant, length, mult, zl_len, side)
    return P.simulate(D['o'], D['h'], D['l'], D['c'], sig, nan, nan, xl, xs, 10 ** 9)


def fmt(r):
    return f"PF {min(r['pf'], 99):.2f}, {r['per_year']:.0f}/yr, win {r['win']:.0f}%, {r['ret']:+.0f}%, DD {r['dd']:.0f}%"


if __name__ == '__main__':
    print('# Chandelier Exit + ZLSMA, Bybit BTCUSDT perpetual\n')
    print('Generated by `scripts/chandelier_zlsma.py`. Chandelier Exit (everget, close-based extremes) with veryfid\'s '
          'ZLSMA (source close, offset 0). Signal on the close, fill at the next open, 0.075% per side, 1x. '
          'Train Apr 2020 – Oct 2024 (1D from Jan 2021), test Oct 2024 – Oct 2026.\n')
    print('- **ce**: Chandelier alone. **filter**: Buy only above ZLSMA, Sell only below; exit on the opposite CE signal.\n'
          '- **filter_zlexit**: filter + exit when the close crosses back through ZLSMA.\n'
          '- **confirm**: enter when CE direction and close vs ZLSMA first agree; exit when CE flips. '
          '**confirm_zlexit**: exit as soon as either disagrees.\n')
    summary = []
    for tf in TFS:
        D = P.prepare(P.load('data', tf))
        t = D['t']
        W = C.windows(t)
        W['full'] = (300, len(t))
        print(f'## {tf}, ZLSMA 38\n\n| CE | Side | Variant | Train | Test | Whole period |\n|---|---|---|---|---|---|')
        for n, k in CE_SETTINGS:
            for side in ('both', 'long'):
                for v in VARIANTS:
                    tr = run(D, v, n, k, 38, side)
                    r = {w: P.stats(t, tr, s, e) for w, (s, e) in W.items()}
                    summary.append((tf, n, k, side, v, r))
                    print(f"| {n}/{k:g} | {side} | {v} | {fmt(r['train'])} | {fmt(r['test'])} | {fmt(r['full'])} |")
        print(f"\nBuy & hold {tf}: whole period {(D['c'][-1] / D['c'][300] - 1) * 100:+.0f}%\n")
        print(f'ZLSMA length check ({tf}, test-window PF, CE 22/3, both sides):\n')
        print('| Variant | ' + ' | '.join(f'ZLSMA {z}' for z in (20, 32, 38, 50, 75, 100)) + ' |\n|---|' + '---|' * 6)
        for v in VARIANTS[1:]:
            print(f'| {v} | ' + ' | '.join(f"{P.stats(t, run(D, v, 22, 3.0, z, 'both'), *W['test'])['pf']:.2f}"
                                           for z in (20, 32, 38, 50, 75, 100)) + ' |')
        print()
    print('## Does ZLSMA 38 help? Test-window PF vs Chandelier alone\n')
    print('| TF | CE | Side | CE alone | Best ZLSMA variant | Its test PF | Its train PF |\n|---|---|---|---|---|---|---|')
    for tf in TFS:
        for n, k in CE_SETTINGS:
            for side in ('both', 'long'):
                rows = [x for x in summary if x[0] == tf and x[1] == n and x[2] == k and x[3] == side]
                base = next(x for x in rows if x[4] == 'ce')[5]
                best = max((x for x in rows if x[4] != 'ce'), key=lambda x: x[5]['train']['pf'])
                print(f"| {tf} | {n}/{k:g} | {side} | {base['test']['pf']:.2f} | {best[4]} (best on train) | "
                      f"{best[5]['test']['pf']:.2f} | {best[5]['train']['pf']:.2f} |")
