"""Chandelier Exit + ZLSMA 38 + MACD on Bybit BTCUSDT perpetual. Needs numpy.

MACD(12, 26, 9) on close agrees with a long when:
  hist  MACD line > signal line            zero  MACD line > 0
(shorts mirrored). Variants (signal on the close, fill at the next open, 0.075% per side, 1x, full equity):
  ce              Chandelier Exit alone (long on Buy, short on Sell)
  ce_zl           CE signal only if close is on the right side of ZLSMA 38; exit on the opposite CE signal
  ce_macd         CE signal only if MACD agrees
  ce_zl_macd      CE signal only if ZLSMA and MACD both agree on that candle
  confirm3        enter when CE direction, close vs ZLSMA and MACD first all agree; exit when CE flips
  confirm3_mexit  confirm3, but also exit when MACD turns against the trade
Train Apr 2020 - Oct 2024 (Jan 2021 on 1D), test Oct 2024 - Oct 2026.

    python3 scripts/chandelier_zlsma_macd.py > backtests/chandelier_zlsma_macd.md
"""
import os, sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from chandelier_zlsma import C, P, ce_dir, zlsma  # noqa: E402

TFS = ('15m', '1H', '4H', '12H', '1D')
CE_SETTINGS = ((22, 3.0), (40, 4.0))
VARIANTS = [('ce', None), ('ce_zl', None)] + [(v, m) for v in ('ce_macd', 'ce_zl_macd', 'confirm3', 'confirm3_mexit')
                                              for m in ('hist', 'zero')]


def macd(c, fast=12, slow=26, sig=9):
    m = P.ema(c, fast) - P.ema(c, slow)
    return m, P.ema(m, sig)


def signals(D, variant, mode, length, mult, side, zl_len=38, macd_set=(12, 26, 9)):
    c = D['c']
    buy, sell, d = ce_dir(D, length, mult)
    zl = zlsma(c, zl_len)
    zup, zdn = c > zl, c < zl
    m, s = macd(c, *macd_set)
    mup, mdn = ((m > s), (m < s)) if mode == 'hist' else ((m > 0), (m < 0))
    if variant == 'ce':
        el, es, xl, xs = buy, sell, sell, buy
    elif variant == 'ce_zl':
        el, es, xl, xs = buy & zup, sell & zdn, sell, buy
    elif variant == 'ce_macd':
        el, es, xl, xs = buy & mup, sell & mdn, sell, buy
    elif variant == 'ce_zl_macd':
        el, es, xl, xs = buy & zup & mup, sell & zdn & mdn, sell, buy
    else:
        al, as_ = (d == 1) & zup & mup, (d == -1) & zdn & mdn
        el, es = al & ~np.r_[False, al[:-1]], as_ & ~np.r_[False, as_[:-1]]
        xl, xs = (d == -1), (d == 1)
        if variant == 'confirm3_mexit':
            xl, xs = xl | mdn, xs | mup
    if side == 'long':
        es = np.zeros(len(c), bool)
    sig = np.where(el, 1, np.where(es, -1, 0))
    sig[:300] = 0
    return sig, xl, xs


def run(D, variant, mode, length, mult, side, **kw):
    sig, xl, xs = signals(D, variant, mode, length, mult, side, **kw)
    nan = np.full(len(sig), np.nan)
    return P.simulate(D['o'], D['h'], D['l'], D['c'], sig, nan, nan, xl, xs, 10 ** 9)


def fmt(r):
    return f"PF {min(r['pf'], 99):.2f}, {r['per_year']:.0f}/yr, win {r['win']:.0f}%, {r['ret']:+.0f}%, DD {r['dd']:.0f}%"


def name(v, m):
    return v if m is None else f'{v} ({m})'


if __name__ == '__main__':
    print('# Chandelier Exit + ZLSMA 38 + MACD, Bybit BTCUSDT perpetual\n')
    print('Generated by `scripts/chandelier_zlsma_macd.py`. MACD 12 / 26 / 9 on close; **hist** = MACD line vs signal '
          'line, **zero** = MACD line vs 0. Signal on the close, fill at the next open, 0.075% per side, 1x. '
          'Train Apr 2020 – Oct 2024 (1D from Jan 2021), test Oct 2024 – Oct 2026.\n')
    best_rows = []
    for tf in TFS:
        D = P.prepare(P.load('data', tf))
        t = D['t']
        W = C.windows(t)
        W['full'] = (300, len(t))
        print(f'## {tf}\n\n| CE | Side | Variant | Train | Test | Whole period |\n|---|---|---|---|---|---|')
        for n, k in CE_SETTINGS:
            for side in ('both', 'long'):
                rows = []
                for v, m in VARIANTS:
                    tr = run(D, v, m, n, k, side)
                    r = {w: P.stats(t, tr, s, e) for w, (s, e) in W.items()}
                    rows.append((v, m, r))
                    print(f"| {n}/{k:g} | {side} | {name(v, m)} | {fmt(r['train'])} | {fmt(r['test'])} | {fmt(r['full'])} |")
                base = rows[0][2]
                pick = max(rows[1:], key=lambda x: x[2]['train']['pf'] if x[2]['train']['n'] >= 10 else 0)
                best_rows.append((tf, n, k, side, base, pick))
        print(f"\nBuy & hold {tf}, whole period: {(D['c'][-1] / D['c'][300] - 1) * 100:+.0f}%\n")
    print('## Summary: Chandelier alone vs the best combination (picked on train), test window\n')
    print('| TF | CE | Side | CE alone: test PF | Best combo on train | Its train PF | Its test PF | Its whole-period return |')
    print('|---|---|---|---|---|---|---|---|')
    for tf, n, k, side, base, (v, m, r) in best_rows:
        print(f"| {tf} | {n}/{k:g} | {side} | {base['test']['pf']:.2f} | {name(v, m)} | {r['train']['pf']:.2f} | "
              f"{r['test']['pf']:.2f} | {r['full']['ret']:+.0f}% |")
