"""RSI pullback with limit orders on Bybit BTCUSDT perpetual: the best candidate from pf_search.py, tested
with realistic order fills. Needs numpy and data/bybit_15m.json (scripts/bybit_data.py).

Rules (long; short is the mirror image):
  signal   on a candle close: RSI(n) < lo and close > EMA(trend)
  entry    buy LIMIT at close - off x ATR(14), valid for the next candle only. Filled only if that candle
           trades BELOW the limit (touching is not enough), at the limit price, maker fee.
  exit     when RSI(n) closes above 50: sell LIMIT at that close for the next candle (filled if the candle
           trades above it, maker fee); if not filled, sell at that candle's close (taker).
  stop     entry - sl x ATR(14), stop-market (taker + slippage, fills at the open if it gaps through).
  time     out at market (taker) after max_bars candles.
Fees: maker 0.02%, taker 0.055% + 0.02% slippage per side. 1x, full equity per trade.

    python3 scripts/rsi_pullback.py               # grid on 15m / 1H / 4H, train 2020-24, test 2024-26
"""
import argparse, itertools, os, sys, time
from multiprocessing import Pool

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pf_search import DAY, atr, ema, load, rsi  # noqa: E402

MAKER, TAKER = 0.0002, 0.00075
GRID = dict(n=(2, 3, 4, 5), lo=(15, 20, 25, 30), trend=(20, 50, 100, 200), off=(0.0, 0.1, 0.25),
            sl=(2.0, 3.0, 4.0), max_bars=(12, 48))


def simulate(D, n, lo, trend, off, sl, max_bars, start=300):
    o, h, l, c, A = D['o'], D['h'], D['l'], D['c'], D['atr']
    R, E = D[f'rsi{n}'], D[f'ema{trend}']
    N = len(c)
    trades = []  # (entry bar, net return, entry fee type)
    i = start
    while i < N - 2:
        d = 1 if (R[i] < lo and c[i] > E[i]) else -1 if (R[i] > 100 - lo and c[i] < E[i]) else 0
        if not d:
            i += 1
            continue
        lim = c[i] - d * off * A[i]
        j = i + 1
        if not ((l[j] < lim) if d == 1 else (h[j] > lim)):
            i += 1           # not filled: order cancelled
            continue
        px, stop = lim, lim - d * sl * A[i]
        fee_in, ex, fee_out, k = MAKER, None, TAKER, j
        while k < N:
            if (l[k] <= stop) if d == 1 else (h[k] >= stop):
                if k == j and ((o[k] <= stop) if d == 1 else (o[k] >= stop)):
                    ex = stop    # filled below the stop on the entry candle: stopped at the stop
                else:
                    ex = min(stop, o[k]) if d == 1 else max(stop, o[k])
                break
            if k + 1 >= N:
                ex = c[k]
                break
            if (R[k] > 50) if d == 1 else (R[k] < 50):
                tgt = c[k]
                if (h[k + 1] > tgt) if d == 1 else (l[k + 1] < tgt):
                    ex, fee_out = tgt, MAKER
                else:
                    ex = c[k + 1]
                k += 1
                break
            if k - j + 1 >= max_bars:
                ex = c[k]
                break
            k += 1
        trades.append((j, d * (ex / px - 1) - fee_in - fee_out, fee_out == MAKER))
        i = k
    return trades


def stats(t, trades, s, e):
    r = np.array([x[1] for x in trades if s <= x[0] < e])
    years = (t[e - 1] - t[s]) / DAY / 365
    if not len(r):
        return dict(n=0, per_year=0, pf=0, win=0, ret=0, dd=0, maker_exit=0)
    eq = np.cumprod(1 + r)
    dd = 1 - eq / np.maximum.accumulate(np.r_[1, eq])[1:]
    loss = -r[r <= 0].sum()
    return dict(n=len(r), per_year=len(r) / years, pf=r[r > 0].sum() / loss if loss else 99, win=100 * (r > 0).mean(),
                ret=100 * (eq[-1] - 1), dd=100 * dd.max(),
                maker_exit=100 * np.mean([x[2] for x in trades if s <= x[0] < e]))


def prepare(candles):
    t, o, h, l, c, v = candles.T
    D = dict(t=t, o=o, h=h, l=l, c=c, atr=atr(h, l, c, 14))
    for n in GRID['n']:
        D[f'rsi{n}'] = rsi(c, n)
    for n in GRID['trend']:
        D[f'ema{n}'] = ema(c, n)
    return D


G = {}


def init(D, W):
    G['D'], G['W'] = D, W


def run(p):
    tr = simulate(G['D'], **p)
    return p, {w: stats(G['D']['t'], tr, s, e) for w, (s, e) in G['W'].items()}


def fmt(r):
    return f"PF {r['pf']:.2f}, {r['per_year']:.0f}/yr, win {r['win']:.0f}%, {r['ret']:+.0f}%, DD {r['dd']:.0f}%"


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--data', default='data')
    ap.add_argument('--tf', nargs='*', default=['15m', '1H', '4H'])
    a = ap.parse_args()
    combos = [dict(zip(GRID, v)) for v in itertools.product(*GRID.values())]
    print('# RSI pullback with limit orders, Bybit BTCUSDT perpetual\n')
    print('Generated by `scripts/rsi_pullback.py`. Limit entries fill only when price trades through them; '
          'stops and time exits pay taker + slippage.\n')
    for tf in a.tf:
        candles = load(a.data, tf)
        t = candles[:, 0]
        split = int(np.searchsorted(t, t[-1] - 2 * 365 * DAY))
        W = {'train': (300, split), 'test': (split, len(t))}
        with Pool(os.cpu_count(), initializer=init, initargs=(prepare(candles), W)) as pool:
            res = pool.map(run, combos, chunksize=8)
        ok = [x for x in res if x[1]['train']['per_year'] >= 250 and x[1]['test']['per_year'] >= 250]
        d0 = time.strftime('%Y-%m-%d', time.gmtime(t[split] / 1000))
        print(f'## {tf} (test from {d0}): {len(ok)} of {len(res)} settings trade 250+ times a year in both windows\n')
        print('| n | lo | trend | off | sl | max | Train | Test | Test maker exits |\n|---|---|---|---|---|---|---|---|---|')
        for p, r in sorted(ok, key=lambda x: -x[1]['train']['pf'])[:10]:
            print(f"| {p['n']} | {p['lo']} | {p['trend']} | {p['off']} | {p['sl']} | {p['max_bars']} | "
                  f"{fmt(r['train'])} | {fmt(r['test'])} | {r['test']['maker_exit']:.0f}% |")
        print()
